# Generated by Django 4.2.4 on 2023-09-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resetpasswordnumbermodel',
            old_name='username',
            new_name='email',
        ),
    ]
