# Generated by Django 4.2.4 on 2023-09-03 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profilemodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='username',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
