# Generated by Django 4.2.4 on 2023-09-08 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_profilemodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='nickname',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', related_query_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
