# Generated by Django 4.2.4 on 2023-09-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profilemodel_user_id_profilemodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
