# Generated by Django 4.2.4 on 2023-09-09 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_profilemodel_user_resetpasswordnumbermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetpasswordnumbermodel',
            name='attempt',
        ),
    ]
