# Generated by Django 4.2.4 on 2023-09-09 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_resetpasswordnumbermodel_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordnumbermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
