# Generated by Django 4.2.4 on 2023-09-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_resetpasswordnumbermodel_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='username',
        ),
    ]
